# Generated by Django 3.2.5 on 2022-03-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0002_userpangolin_my_date_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpangolin',
            name='age',
        ),
    ]
