# Generated by Django 3.2.5 on 2022-03-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0005_alter_userpangolin_my_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpangolin',
            name='friends',
            field=models.ManyToManyField(blank=True, to='pangolin.UserPangolin'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='pangolin.userpangolin')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='pangolin.userpangolin')),
            ],
        ),
    ]
