# Generated by Django 3.2.5 on 2022-03-18 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0007_alter_userpangolin_my_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpangolin',
            name='my_date_field',
            field=models.DateField(default=datetime.date(2022, 3, 18)),
        ),
    ]
