# Generated by Django 3.2.5 on 2022-03-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0011_alter_loggeduser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pangolin.userpangolin'),
        ),
    ]
