# Generated by Django 3.2.5 on 2022-03-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0014_alter_userpangolin_my_date_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
