# Generated by Django 3.2.5 on 2022-03-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0016_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='comentarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pangolin.comentario'),
        ),
    ]
