# Generated by Django 3.2.5 on 2022-03-22 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0020_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpangolin',
            name='my_date_field',
            field=models.DateField(default=datetime.date(2022, 3, 22)),
        ),
    ]
